### PR TITLE
[DPC-2305] Update Ruby Active Gems

### PR DESCRIPTION
**Pull request by TiannaW24**
### Proposed Changes

* Update Ruby Active Gems from 6.1.4.6 -> 6.1.4.7 based on guidance from https://groups.google.com/g/rubyonrails-security/c/n-p-W1yxatI
* Apply Rubocop suggestions for /model/user.rb in dpc-web and dpc-admin

### Security Implications

- [X] new software dependencies

### CODE REVIEW

**Comment by famegashie** [comment]
Reviewed.

**Review by famegashie — APPROVED** [review]
Reviewed.

**Review by togunsola — APPROVED** [review]

**Review by famegashie — APPROVED** [review]
Reviewed.

**Review by togunsola — COMMENTED** [review]
Reviewed

**Pull request merged**
