### PR TITLE
PLT-295 Add opt-out-import lambda code from dpc-ops

### PR DESCRIPTION
**Pull request by gsf**
## 🎫 Ticket

https://jira.cms.gov/browse/PLT-295

## 🛠 Changes

Added code for the opt-out-import lambda.

## ℹ️ Context for reviewers

Code for the opt-out-import lambda is being [removed from dpc-ops](https://github.com/CMSgov/dpc-ops/pull/660) and added to dpc-app to allow separation of concerns. The DPC team is responsible for the code in the lambda, and will test and deploy that code from this dpc-app repo.

## ✅ Acceptance Validation

The next PR will put workflows into place for tests and deploys.

## 🔒 Security Implications

- [x] This PR requires additional review of its security implications for other reasons.

Given that we are moving software from a private repo to a public one, I have reviewed for any sensitive information, but I've added @StewGoin for awareness.

### CODE REVIEW

**Review by Miki543 — APPROVED** [review]

**Review by MEspositoE14s — APPROVED** [review]
Looks good to me.  If you pull in the changes from https://github.com/CMSgov/dpc-app/pull/2033 it will fix the failing checks.  Also, I know you have another PR coming, but once everything is said and done will we have to do anything different to deploy the opt out scripts or just push changes to main?

Lastly, for @CMSgov/dpc-dev, should we open another ticket to try and address some of the suggestions from CodeClimate?  I don't necessarily agree with all of them, and I'm not sure how they define "cognitive complexity", but it might be worth looking into.

**Comment by gsf** [comment]
> Looks good to me. If you pull in the changes from #2033 it will fix the failing checks. Also, I know you have another PR coming, but once everything is said and done will we have to do anything different to deploy the opt out scripts or just push changes to main?

Great I'll pull in those changes. And yes, the other incoming PR will set up workflows to test and deploy automatically. Specifically:

* PR changes to the lambda code will run lambda unit and coverage tests
* Lambda code merged to main will be automatically deployed to the test environment
* Deploys to dev and upper environments will be manually-triggered workflows

I also have future work scheduled to set up integration tests in the test environment.

**Review by StewGoin — APPROVED** [review]
👍

**Comment by gsf** [comment]
I'm thinking that the binary `bin/bootstrap` should not be in the repo. Any reason to keep it in?

**Comment by gsf** [comment]
Okay I think this is good to merge. The unit tests are failing but we'll need to make a decision there: either set up a role for these tests to assume to access S3 or rewrite unit tests to avoid reaching out to AWS resources. All deploy workflows have been run against this branch with success.

**Comment by kyeah** [comment]
> The unit tests are failing but we'll need to make a decision there: either set up a role for these tests to assume to access S3 or rewrite unit tests to avoid reaching out to AWS resources. 

I haven't looked closely at the failures, but just to clarify — the unit tests should be talking to the localstack instance of S3, not actual AWS S3. I'm guessing maybe when AWS credentials are configured on the host that the application code is incorrectly utilizing those credentials instead of talking to localstack.

**Pull request merged**
