### PR TITLE
DPC-714 output operation outcome for patient/resource pair when look back fails

### PR DESCRIPTION
**Pull request by whuang85**
### Fixes [DPC-714](https://jira.cms.gov/browse/DPC-714)

Need to return an operation outcome when look back fails either because it couldn't get any EoBs for the patient or because no EoB's matched look back criteria

### Proposed Changes

* Change LookBack Service to return the LookBackAnswer for each EOB
* Collect the EOB's of a patient
* Before fetching the patient's resources, analyze the collection of EoB's to see if they pass look back, if failed, create a OperationOutcome resource
* Write the resources from the step above

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation

The postman collection test creates a submitted roster with 
`"3S58A00AA00", "4S58A00AA00", "5S58A00AA00", "0S80C00AA00"`

The postman collection uses the mock blue button client which only had data on
`"3S58A00AA00", "4S58A00AA00", "5S58A00AA00"`

Therefore `"0S80C00AA00"` will not have data for look back
```
{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"exception","details":{"text":"Failed to get data for look back"},"location":["Patient","id","0S80C00AA00"]}]}

```

### CODE REVIEW

**Comment by embh** [comment]
This looks good. Is there anything we can use for Acceptance Validation? Maybe test results like this? https://github.com/CMSgov/dpc-app/pull/1058/files#diff-418a41c6b353afb120cabe81362f9772R561

**Comment by whuang85** [comment]
> This looks good. Is there anything we can use for Acceptance Validation? Maybe test results like this? https://github.com/CMSgov/dpc-app/pull/1058/files#diff-418a41c6b353afb120cabe81362f9772R561

Like check the content of the files?

**Comment by embh** [comment]
> > This looks good. Is there anything we can use for Acceptance Validation? Maybe test results like this? https://github.com/CMSgov/dpc-app/pull/1058/files#diff-418a41c6b353afb120cabe81362f9772R561
> 
> Like check the content of the files?

That would work, or even just linking to the lines in the tests with a note that they confirm that the OperationOutcome is being generated. I think our goal is to demonstrate how we know that the changes are working.

**Comment by whuang85** [comment]
> > > This looks good. Is there anything we can use for Acceptance Validation? Maybe test results like this? https://github.com/CMSgov/dpc-app/pull/1058/files#diff-418a41c6b353afb120cabe81362f9772R561
> > 
> > 
> > Like check the content of the files?
> 
> That would work, or even just linking to the lines in the tests with a note that they confirm that the OperationOutcome is being generated. I think our goal is to demonstrate how we know that the changes are working.

Aren't those tests doing that?  I'll add a check in the e2e.  We check EoB, Patient, and Coverage on export, will also check the OperationOutcome

**Comment by embh** [comment]
> > > > This looks good. Is there anything we can use for Acceptance Validation? Maybe test results like this? https://github.com/CMSgov/dpc-app/pull/1058/files#diff-418a41c6b353afb120cabe81362f9772R561
> > > 
> > > 
> > > Like check the content of the files?
> > 
> > 
> > That would work, or even just linking to the lines in the tests with a note that they confirm that the OperationOutcome is being generated. I think our goal is to demonstrate how we know that the changes are working.
> 
> Aren't those tests doing that? I'll add a check in the e2e. We check EoB, Patient, and Coverage on export, will also check the OperationOutcome

Yep! Sorry, I meant specifically in the Acceptance Validation section of the description.

**Review by SalGutierrez — APPROVED** [review]
🚀 🌚

**Review by embh — APPROVED** [review]
😎

**Pull request merged**
