### PR TITLE
DPC-3670: Comment out loading of sundial

### PR DESCRIPTION
**Pull request by Miki543**
## 🎫 Ticket

https://jira.cms.gov/browse/DPC-3670

## 🛠 Changes

- Commentted out loading of sundial in DPCConsentService.java

## ℹ️ Context for reviewers

(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)

## ✅ Acceptance Validation

compiled and ran tests

## 🔒 Security Implications

- [ ] This PR adds a new software dependency or dependencies.
- [ ] This PR modifies or invalidates one or more of our security controls.
- [ ] This PR stores or transmits data that was not stored or transmitted before.
- [ ] This PR requires additional review of its security implications for other reasons.

If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without his approval.

### CODE REVIEW

**Comment by kyeah** [comment]
@MEspositoE14s yeah that's a great point. I'd love to remove the POST endpoint and any code or documentation that references it — it can fit into this ticket or we can make a followup.

@Miki543 You'll want to remove the sundial imports at the top of the file, the linter isn't happy about those 😄 And then you can remove anything that references sundial in dpc-consent, e.g.

- References in the pom.xml, configuration, and application.conf
- You can remove the `jobs` directory entirely, which has "Suppression" files that are unused.

Thank you!

**Comment by Miki543** [comment]
@kyeah Sounds good! Should I just comment it all out or just go ahead and delete?

**Comment by kyeah** [comment]
@Miki543 You can go ahead and delete, thank you!

**Review by kyeah — APPROVED** [review]
Thanks! I think you can still remove `jobs.xml` (I assume the tests were previously failing because of the removal of the API endpoints, so we can keep those.)

**Pull request merged**
