### PR TITLE
Install a specific Jykll version for dpc-web

### PR DESCRIPTION
**Pull request by TiannaW24**
## Change Details

* Update the dpc-web Dockerfile to install a specific version of Jekyll 

## Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] PHI/PII is affected by this change

### CODE REVIEW

**Comment by lgarceau768** [comment]
Works good, whenever Jitpack is up, good to merge!

**Review by lgarceau768 — APPROVED** [review]

**Comment by TiannaW24** [comment]
The jitpack server is down, which is affecting the API build. Jitpack is the tool we use to pull in Maven dependencies. 

https://github.com/jitpack/jitpack.io/issues/5337

**Review by mftcodes — APPROVED** [review]
good to me. Come on Jitpack! Give us a win!

**Review by famegashie — APPROVED** [review]
Reviewed

**Pull request merged**
