### PR TITLE
create custom layout to parse json like strings for logging

### PR DESCRIPTION
**Pull request by whuang85**
**Why**

There are metrics logs that have a json like structure shoved into the message field of the logs, this PR is to extract out those json like structures and move the key/value pair to the same level as the message field.

**What Changed**

Created a new logback layout that extends EventJsonLayout and currently configured dpc-api to use that new layout

**Choices Made**

This seemed to be the most straight forward way to plug into dropwizard and modify the log messages. Another alternative would be creating a custom appender but I believe that would not give you the LoggingEvent object like it does in the Layout.

**Tickets closed**:

https://jiraent.cms.gov/browse/DPC-1025

**Future Work**

List any additional tickets that have either been created due to work in this PR, or existing tickets that expand upon the feature or provide additional fixes.

**Checklist**

- [x] All tests are passing via `make ci-app` (app change) and `make ci-web` (website change)
- [ ] Swagger documentation has been updated
- [ ] FHIR documentation has been updated
- [ ] Any required dpc-ops changes have a PR submitted and mentioned in this ticket
- [ ] Any manual migration steps are documented, scripts written (where applicable), and tested
- [ ] Before merging, any required dpc-ops changes have been approved and merged into master of the dpc-ops repo

Image below shows `type`, `name`, and `value` at the same level as the other fields, they used to be all stored in the `message` field
Screen Shot 2020-02-18 at 1 35 18 PM

### CODE REVIEW

**Comment by embh** [comment]
Looking good! Do you mind adding a screenshot so we can see the new format in the logs?

**Comment by whuang85** [comment]
> Looking good! Do you mind adding a screenshot so we can see the new format in the logs?

by chance do you know of a good image hosting site for my screen shots?

**Comment by nickrobison-usds** [comment]
One more request. Let's go ahead and roll this out for all of our other services as well. I'd like to get all the logs working at once, if possible.

**Comment by embh** [comment]
> > Looking good! Do you mind adding a screenshot so we can see the new format in the logs?
> 
> by chance do you know of a good image hosting site for my screen shots?

You should be able to drag an image into the description to have it uploaded automatically to GitHub. Let me know if that doesn't work though!

**Pull request merged**
